[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython==3.0.11",
    "numpy==1.26.0",
    "packaging==24.2",
]

[flake8]
max-line-length=120

[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
